(()=>{'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const state={demoStarted:false,step:null,consent:localStorage.getItem('sera-consent')};
function track(event,properties={}){if(state.consent!=='analytics')return;window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...properties,timestamp:new Date().toISOString()})}
window.seraTrack=track;
function addAmbientMotion(){const targets=[['.hero','hero-orbits',12],['.demo-section','demo-orbits',8],['.ai-agent','agent-orbits',7],['.pricing-section','pricing-orbits',9]];targets.forEach(([selector,className,count])=>{const host=$(selector);if(!host)return;const layer=document.createElement('div');layer.className=`ambient-motion ${className}`;layer.setAttribute('aria-hidden','true');layer.innerHTML='<span class="orbit-ring ring-one"><i></i></span><span class="orbit-ring ring-two"><i></i></span><span class="light-arc arc-one"></span><span class="light-arc arc-two"></span><span class="mechanical-gear gear-one"><i></i></span><span class="mechanical-gear gear-two"><i></i></span><span class="mechanical-gear gear-three"><i></i></span>'+Array.from({length:count},(_,i)=>`<b class="float-particle particle-${i+1}"></b>`).join('');host.prepend(layer)})}addAmbientMotion();
const header=$('.site-header'); if(header){addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});$('.menu-toggle')?.addEventListener('click',e=>{const open=header.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});$$('#site-nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('open')))}
const observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');observer.unobserve(x.target)}}),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));
$$('.track-trial').forEach(a=>a.addEventListener('click',()=>track('free_trial_button_clicked',{label:a.textContent.trim()})));$$('.track-demo').forEach(a=>a.addEventListener('click',()=>track('book_demo_button_clicked')));
$$('.faq-list details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)track('faq_opened',{question:$('summary',d)?.textContent})}));
const pricing=$('#pricing-grid');let billing='monthly';
function money(n){return new Intl.NumberFormat('en-MT',{style:'currency',currency:'EUR',minimumFractionDigits:Number.isInteger(n)?0:2,maximumFractionDigits:2}).format(n)}
function portfolioRate(properties){return SERA_CONFIG.portfolioDiscounts.find(b=>properties>=b.min&&properties<=b.max)?.rate||0}
function renderPricing(){if(!pricing||!window.SERA_CONFIG)return;pricing.innerHTML=SERA_CONFIG.plans.filter(p=>p.active).map(p=>{const annual=billing==='annual',amount=annual?p.monthlyPerProperty*12*(1-SERA_CONFIG.annualDiscount):p.monthlyPerProperty,period=annual?'/ property/year':'/ property/month',sub=annual?`${money(amount/12)} effective monthly · 10% annual saving`:'Standard price for 1–2 active properties';return `<article class="price-card ${p.popular?'popular':''}">${p.popular?'<span class="popular-tag">MOST POPULAR</span>':''}<span class="tier">${p.professionalAI?'PROFESSIONAL':'BASIC'}</span><h3>${p.name}</h3><p>${p.description}</p><div class="price"><small>From</small> <strong>${money(amount)}</strong> <small>${period}</small></div><div class="price-sub">${sub}<br>excluding VAT</div><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><a class="btn ${p.popular?'btn-gold':'btn-outline'} plan-select" href="contact.html?intent=trial&plan=${p.code}" data-plan="${p.code}">Start my 30-day free trial</a></article>`}).join('');$$('.plan-select',pricing).forEach(a=>a.addEventListener('click',()=>track('pricing_plan_selected',{plan:a.dataset.plan,billing}))) }
function renderCalculator(){const result=$('#calculator-result'),planCode=$('#calc-plan')?.value,properties=Number($('#calc-properties')?.value||1),period=$('#calc-billing')?.value||'monthly';if(!result||!planCode)return;const plan=SERA_CONFIG.plans.find(p=>p.code===planCode);if(properties>=SERA_CONFIG.customQuoteThreshold){result.innerHTML='<span class="calc-tag">CUSTOM PORTFOLIO</span><h3>Let’s build the right commercial plan.</h3><p>More than 10 active properties require a tailored quotation and onboarding assessment.</p><a class="btn btn-gold" href="contact.html?intent=portfolio&plan=custom">Request a portfolio assessment →</a>';return}const rate=portfolioRate(properties),standardMonthly=plan.monthlyPerProperty*properties,monthlyPortfolioSaving=standardMonthly*rate,discountedMonthly=standardMonthly-monthlyPortfolioSaving,isAnnual=period==='annual',periodMultiplier=isAnnual?12:1,portfolioSaving=monthlyPortfolioSaving*periodMultiplier,preAnnual=discountedMonthly*12,annualBillingSaving=isAnnual?preAnnual*SERA_CONFIG.annualDiscount:0,subtotal=isAnnual?preAnnual-annualBillingSaving:discountedMonthly,vat=subtotal*SERA_CONFIG.vatRate,total=subtotal+vat,annualSaving=isAnnual?(standardMonthly*12-subtotal):monthlyPortfolioSaving*12,periodLabel=isAnnual?'Annual payment':'Monthly payment';result.innerHTML=`<span class="calc-tag">YOUR ESTIMATE</span><h3>${plan.name} · ${properties} ${properties===1?'property':'properties'}</h3><dl><div><dt>Standard property charge</dt><dd>${money(plan.monthlyPerProperty)} × ${properties}</dd></div><div><dt>Portfolio discount</dt><dd>${rate?`${rate*100}% · −${money(portfolioSaving)}`:'Not applicable'}</dd></div>${isAnnual?`<div><dt>Annual billing discount</dt><dd>10% · −${money(annualBillingSaving)}</dd></div>`:''}<div class="calc-subtotal"><dt>Subtotal excluding VAT</dt><dd>${money(subtotal)}</dd></div><div><dt>VAT (${SERA_CONFIG.vatRate*100}%)</dt><dd>${money(vat)}</dd></div><div class="calc-total"><dt>Total including VAT</dt><dd>${money(total)}</dd></div></dl><div class="calc-foot"><span>${periodLabel}</span><strong>Total annual saving: ${money(annualSaving)}</strong></div><a class="btn btn-gold" href="contact.html?intent=trial&plan=${plan.code}&billing=${period}">Start my 30-day free trial →</a>`}
const calcShell=$('#portfolio-calculator');if(calcShell)calcShell.insertAdjacentHTML('beforebegin','<div class="billing-benefits"><article><strong>Monthly billing</strong><p>Flexible monthly payments, ongoing access, approved information updates and pricing that adjusts when active properties change.</p></article><article><strong>Annual billing · save 10%</strong><p>Paid in advance after portfolio discounts, with price protection, a priority annual account review and one planned property-information review.</p></article></div>');const commercial=$('.commercial-note');if(commercial)commercial.textContent+=' A property is active when SERA is configured to provide guest support for it. Paid billing begins from the agreed live-service date—not when an enquiry is submitted.';renderPricing();renderCalculator();$$('[data-billing]').forEach(b=>b.addEventListener('click',()=>{billing=b.dataset.billing;$$('[data-billing]').forEach(x=>x.classList.toggle('active',x===b));if($('#calc-billing'))$('#calc-billing').value=billing;renderPricing();renderCalculator();track(`${billing}_billing_selected`)}));$$('#portfolio-calculator select').forEach(s=>s.addEventListener('change',()=>{renderCalculator();track('portfolio_calculator_updated',{plan:$('#calc-plan').value,properties:$('#calc-properties').value,billing:$('#calc-billing').value})}));
if($('#pricing')){new IntersectionObserver(e=>{if(e[0].isIntersecting){track('user_reached_pricing_section');e[0].target.dataset.seen='true'}},{threshold:.25}).observe($('#pricing'))}
const chat=$('#chat-area'),form=$('#demo-form'),input=$('#demo-question'),quick=$('#quick-replies');
const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function bubble(text,type='sera',extra=''){if(!chat)return;const el=document.createElement('div');el.className=`bubble ${type} ${extra}`;el.innerHTML=`${text}<time>${now()}${type==='sera'?' ✓✓':''}</time>`;chat.append(el);chat.scrollTop=chat.scrollHeight}
function typing(){const el=document.createElement('div');el.className='demo-typing';el.innerHTML='<i></i><i></i><i></i>';chat.append(el);chat.scrollTop=chat.scrollHeight;return el}
const replies={
wifi:['The Wi-Fi network is <strong>Seaview Guest</strong> and the password is <strong>WelcomeMalta24</strong>.<br><br>Let me know if you have any trouble connecting.'],
checkout:['Check-out is at <strong>10:00 AM</strong>.<br><br>Please return the keys as explained in your departure instructions and make sure the main door is properly closed.'],
parking:['Free street parking is normally available. The nearest public car park is approximately three minutes away.'],
aircon:['Use the wall controller, select cooling mode and set the temperature between 21°C and 24°C.'],
late:['I can help with that request.<br><br>What time would you like to check out?'],
hotwater:['I’m sorry about that.<br><br>Before I escalate this, can you confirm whether electricity is working normally inside the apartment?'],
locked:['I understand. I will help you with this.<br><br>This demo does not collect personal details. In a live service, SERA would confirm your name, property, whether belongings are inside and whether anyone else is inside.'],
smoke:['<strong>Please move to a safe location immediately.</strong><br><br>If you believe there is a fire or immediate danger, contact emergency services now.<br><br>I am also escalating this as an urgent safety issue.']};
function classify(q){q=q.toLowerCase();if(/smoke|fire|gas smell|burning/.test(q))return'smoke';if(/locked|lock out|outside/.test(q))return'locked';if(/hot water|cold shower/.test(q))return'hotwater';if(/late.*check|check.*late/.test(q))return'late';if(/wi.?fi|internet password/.test(q))return'wifi';if(/check.?out|leave time|departure time/.test(q))return'checkout';if(/park|car/.test(q))return'parking';if(/air.?con|a\/c|cooling/.test(q))return'aircon';return'unknown'}
function respond(q,source='free_text'){if(!q.trim())return;if(!state.demoStarted){state.demoStarted=true;track('demo_started')}track(source==='quick'?'demo_question_selected':'demo_free_text_question_submitted',{question:q});bubble(q,'guest');input.value='';const t=typing();setTimeout(()=>{t.remove();if(state.step==='late-time'){bubble('Thank you. I have sent your request to the property manager for approval.<br><br>Please note that late check-out is not confirmed until the manager approves it.');simEscalation('Approval request · Demo escalation created');state.step=null;return}if(state.step==='hotwater-electricity'){bubble('Did the issue start recently, or has there been no hot water since arrival?');state.step='hotwater-duration';return}if(state.step==='hotwater-duration'){bubble('Thank you. I have prepared the maintenance report and escalated it to the property manager.<br><br><strong>Reference:</strong> Maintenance request submitted.');simEscalation('Maintenance · Demo escalation created');state.step=null;return}const key=classify(q);if(key==='unknown'){bubble('I do not have enough approved information to answer that. I can escalate this request.');return}bubble(replies[key][0],'sera',key==='smoke'?'urgent':'');if(key==='late')state.step='late-time';if(key==='hotwater')state.step='hotwater-electricity';if(key==='locked'){simEscalation('Immediate assistance · Demo escalation created');state.step=null}if(key==='smoke'){simEscalation('Urgent safety issue · Demo escalation created',true);state.step=null}},430)}
function simEscalation(label,urgent=false){setTimeout(()=>{bubble(`<strong>${label}</strong><br>This is a simulation. No real person has been contacted.`,'sera',urgent?'urgent':'system');track('demo_escalation_reached',{urgent});track('demo_completed')},300)}
form?.addEventListener('submit',e=>{e.preventDefault();respond(input.value)});quick?.addEventListener('click',e=>{if(e.target.tagName==='BUTTON')respond(e.target.textContent,'quick')});
$('#restart-demo')?.addEventListener('click',()=>{chat.innerHTML='<div class="day-pill">Today</div>';bubble('Welcome to Seaview Apartment. I’m SERA, your guest concierge. How can I help?');state.step=null;state.demoStarted=false;track('demo_restarted');input.focus()});
const banner=$('#cookie-banner');if(banner&&!state.consent)setTimeout(()=>banner.classList.add('show'),900);function consent(v){state.consent=v;localStorage.setItem('sera-consent',v);banner?.classList.remove('show');if(v==='analytics')track('consent_granted')}$('#cookie-essential')?.addEventListener('click',()=>consent('essential'));$('#cookie-accept')?.addEventListener('click',()=>consent('analytics'));
const contact=$('#contact-form');if(contact){let started=false;contact.addEventListener('focusin',()=>{if(!started){started=true;track('contact_form_started')}},{once:true});const params=new URLSearchParams(location.search),intent=params.get('intent')||'contact',plan=params.get('plan');if($('#intent'))$('#intent').value=intent;if(plan&&$('#preferred-plan'))$('#preferred-plan').value=plan;contact.addEventListener('submit',async e=>{e.preventDefault();if(!contact.checkValidity()){contact.reportValidity();return}const trap=$('#website');if(trap?.value)return;const submit=$('button[type="submit"]',contact),original=submit.textContent;submit.disabled=true;submit.textContent='Sending…';$('.form-error')?.classList.remove('show');const data=Object.fromEntries(new FormData(contact).entries());delete data.website;data.intent=intent;data.source='SERA website';data.submitted_at=new Date().toISOString();try{const endpoints=SERA_CONFIG.integrations||{};if(intent==='trial'){if(!endpoints.trialAppsScript)throw new Error('Trial endpoint is not configured');await fetch(endpoints.trialAppsScript,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(data)})}else{if(!endpoints.formspree)throw new Error('Contact endpoint is not configured');data._subject=`SERA ${intent} enquiry from ${data.name||'website visitor'}`;const response=await fetch(endpoints.formspree,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error(`Formspree returned ${response.status}`)}$('.form-success')?.classList.add('show');contact.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);track(intent==='portfolio'?'portfolio_enquiry_submitted':'contact_form_submitted',{intent,plan:plan||''});$('.form-success')?.scrollIntoView({behavior:'smooth',block:'center'})}catch(error){console.error('SERA form submission failed',error);submit.disabled=false;submit.textContent=original;$('.form-error')?.classList.add('show');$('.form-error')?.scrollIntoView({behavior:'smooth',block:'center'})}})}
const requestedBilling=new URLSearchParams(location.search).get('billing');if(requestedBilling&&$('#billing'))$('#billing').selectedIndex=requestedBilling==='annual'?1:0;
})();
